### ISSUE TITLE
template vs. curve methods

### ISSUE THREAD

**Issue by mdsumner** [rociojoo/CranTaskView-Track#1]
A minor-ish suggestion, we settled on the terminology "curve method" for using multiple data points during a twilight - in all my discussions with folks it seems that only Phil Ekstrom really knows what the "template" is. To us it's curve-fitting.

**Comment by rociojoo** [comment]
OK. I'll change that. Thanks!

**Comment by rociojoo** [comment]
It's done!

**Comment by rociojoo** [comment]
I'll close the issue if there is nothing there to add.

**Comment by mdsumner** [comment]
Yep all good thanks
