### ISSUE TITLE
RNCEP: Obtain, Organize, and Visualize NCEP Weather Data

### ISSUE THREAD

**Issue by rociojoo** [rociojoo/CranTaskView-Track#10]
**Is it on CRAN?**  
Yes. https://cran.r-project.org/web/packages/RNCEP/index.html

**Are you the author of this package?**  
No. 

**If you are the author, does it pass check CRAN tests?**  
I don't know. 

**Additional information:**  
The authors contacted me to include it in the review paper and did not include it because it didn't seem to have tracking data at its core. But one of its main features has to do with tracking data so I'm submitting it to your opinions now. 

Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?  
It's goal is to extract, handle and visualize NCEP weather data. From 7 points describing the package, 3 could be related to tracking data:
5. Query data from these two NCEP datasets interpolated to a particular point in time and space
6. Visualize these interpolated data as points on a map using color to represent the interpolated
value
7. Perform trajectory simulations according to specified behavior using wind data from NCEP or
data specified by the user.
There are references to animal behavior and GPS in its documentation.

In terms of the tracking workflow (see Figure in the CTV), where does the package fit? (Feel free to mention any particular functions and how they fit as well.)
Simulation and others (extracting environmental data)

**Comment by birderboone** [comment]
Thanks Rocio, I added it to the list. I'm not sure if we want to discuss this closer to the next update. My personal opinion, while I love RNCEP, I dont think this is not the taskview for it. Spatio-temporal maybe more suited for it. 

My argument being, that its main purpose is not tracking related even if there is a section associated with tracking. And that the vast majority of the code is for non-tracking related analysis. We should ofcourse try to make it clear where the cut off is, with a package being specifically written for tracking data, or having a large enough section for tracking data to be included.

**Comment by rociojoo** [comment]
After considering @birderboone 's opinion, I think that RNCEP does not belong to this CTV. While there are functions related to tracking data, it is not the main goal of the package. If there were a vignette specific to tracking data, we could reconsider.

**Comment by rociojoo** [comment]
I added `skip = T` for that package to `Tracking_tbl.csv`.
