### ISSUE TITLE
gtfs2gps: Converting Transport Data from GTFS Format to GPS-Like Records

### ISSUE THREAD

**Issue by rafapereirabr** [rociojoo/CranTaskView-Track#12]
**Is it on CRAN?**  
[Yes](https://cran.r-project.org/web/packages/gtfs2gps/index.html)

**Are you the author of this package?**  
Yes. 

**If you are the author, does it pass check CRAN tests?**  
Yes. 

**Additional information:**  
In order to be included in the CTV Tracking, we would appreciate more information to help us determine how the package fits into the Tracking CTV scope.  

Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?  

**gtfs2gps** is an R package that converts public transportation data in GTFS format to GPS-like records in a `data.frame`/`data.table`, which can then be used in various applications such as running transport simulations or scenario analyses. The core function of the package takes a `GTFS.zip` file and interpolates the space-time position of each vehicle in each trip considering the network distance and average speed between stops. The output is a `data.table` where each row represents the timestamp of each vehicle at a given spatial resolution. The package also has some functions to subset GTFS data in time and space and to convert both representations to [simple feature](https://CRAN.R-project.org/package=sf) format.

In terms of the tracking workflow (see Figure in the CTV), where does the package fit? (Feel free to mention any particular functions and how they fit as well.)

The `gtfs2gps` package  creates, transforms and analyses tracking data of public transport networks. It takes as an input a raw data set on the characteristics of public transport networks organized in standard `GTFS` format, which at the core is the geolocated time-table of the planned services of a public transport system. The package then runs a series of functions to interpolate the position of vehicles in space and time at high resolution, creating a data set that is close to a GPS-like representation of the whole transport network. The package has additional functions to build vehicle trajectories using `simple feature` points and linestrings.

This is a quick animated gif of a sample of bus routes in Sao Paulo, Brazil. This gif was created using the `gtfs2gps` package to process the data and `ggplot2` and `ggnamite` for the data visualization.

<img src="https://user-images.githubusercontent.com/7448421/76999865-49d12e80-694f-11ea-80a3-2ee61c253407.gif" width="450">

**Comment by birderboone** [comment]
Thanks for the detailed submission. Looks great! Our next update will be in December. I'll let you know of the status along the way.

**Comment by rafapereirabr** [comment]
Hi all. Any updates on including gtfs2gps to the CRAN task view?

**Comment by basille** [comment]
Hi @rafapereirabr, thanks for the reminder! And our apologies for our silence… We are well overdue an update of the Tracking CTV, but could not do it in time for various reasons. We hope to be able to run it soon (in the coming weeks), and `gtfs2gps` will be up for review then. We'll keep you posted here.

**Comment by rafapereirabr** [comment]
Thanks, and no worries. Keep up the great work.

**Comment by rociojoo** [comment]
@basille I confirm that this package should be accounted for in `Tracking_tbl.csv` and added which categories it corresponds to.

**Comment by rociojoo** [comment]
I have added the package to the new version of the ctv that should be published within a month, I would say. Thank you for your patience!

**Comment by rafapereirabr** [comment]
Thanks! And thank you for maintaining this cran tasl view!

**Comment by basille** [comment]
The updated CTV is finally on-line: https://cran.r-project.org/view=Tracking

See [official announcement on Twitter](https://twitter.com/MathieuBasille/status/1517195178645364739).
