### ISSUE TITLE
bayesmove: Non-Parametric Bayesian Analyses of Animal Movement

### ISSUE THREAD

**Issue by basille** [rociojoo/CranTaskView-Track#13]
**Is it on CRAN?**  
Not yet — currently prepared for submission.

**Are you the author of this package?**  
No. 

**If you are the author, does it pass check CRAN tests?**  
N/A

**Additional information:**  

The package analyze animal movement to identify behaviors in tracks (both breakpoints and the characterization of behaviors) using a non-parametric Bayesian framework, which addresses a number of limitations of existing segmentation methods and state-space models.

Belongs to **Behavioral pattern identification**.

A few functions help preparing the data and belongs to **Post-processing**.

**Comment by rociojoo** [comment]
Thanks for the submission. We will add it to the list of packages to check very soon and keep you updated.

**Comment by rociojoo** [comment]
Added to the new version of the ctv.

**Comment by basille** [comment]
The updated CTV is finally on-line: https://cran.r-project.org/view=Tracking

See [official announcement on Twitter](https://twitter.com/MathieuBasille/status/1517195178645364739).
