### ISSUE TITLE
sftrack: Modern Classes for Tracking and Movement Data

### ISSUE THREAD

**Issue by basille** [rociojoo/CranTaskView-Track#14]
**Is it on CRAN?**  
Yes: https://cran.r-project.org/package=sftrack

**Are you the author of this package?**  
Yes. 

**If you are the author, does it pass check CRAN tests?**  
Yes. 

**Additional information:**  
`sftrack` provides modern classes for tracking and movement data, as well as plotting and description utilities.
It primarily fits into "preprocessing" (format raw data into proper tracking and trajectory data), together with "post-processing" (computation of metrics), "visualization" (base R and `ggplot2`) and "track description" (summary metrics: length and area covered).

**Comment by rociojoo** [comment]
Thanks for the submission. We're adding it to the list of packages to check soon.

**Comment by rociojoo** [comment]
Added to the new version of the ctv.

**Comment by basille** [comment]
The updated CTV is finally on-line: https://cran.r-project.org/view=Tracking

See [official announcement on Twitter](https://twitter.com/MathieuBasille/status/1517195178645364739).
