### ISSUE TITLE
trajectories of what; geographic or cartesian

### ISSUE THREAD

**Issue by edzer** [rociojoo/CranTaskView-Track#2]
You mention "organisms", "individuals", "biologging" and "animals", I would suggest to generalize this to "objects" except for cases where you have to get specific. The CTV is based on a manuscript in "Animal Ecology", but I don't see how (all the) packages focus on animals too, or can't be used for moving non-living things. 

It would also good to point out whether (and which) packages assume 2-D Euclidean (Cartesian) coordinates, and which assume geographic (long/lat) coordinates. I see too many people who assume wrongly that the software does the right thing for their type of coordinates.

**Comment by basille** [comment]
Hey Edzer, regarding your second point above, isn’t it the role of each package, where relevant, to mention this explicitly? It would be a long and tedious task to review all packages with this particular point in mind — to me, that belongs to package documentation and/or warnings in R.

**Comment by edzer** [comment]
> where relevant,

do you know of examples where it isn't?

In case you decide to not do this, it might be relevant to mention the risk, and that this is left to the users to verify.

**Comment by basille** [comment]
I did not think of packages for which  it was not relevant, but I was thinking in terms of package development. Each package could certainly highlight it at the right time in the workflow (plus in the documentation). 

I like the idea of a general warning in the CTV.

**Comment by mdsumner** [comment]
> that this is left to the users to verify.

I agree with that at least, folks use Cartesian coordinates all the time in inappropriate ways. Is UTM ok? No. Is stereographic ok? No.  When and where? Oh maybe that's ok ...  It really matters. 

I agree absolutely that it should be *general*, but beware of shooting from a basis that is extremely poorly held atm.  "Spatial" is no help here.

**Comment by rociojoo** [comment]
I agree with the general warning.

**Comment by rociojoo** [comment]
The warning is in the text now (first paragraph): "Regarding (x,y), some packages may assume 2-D Euclidean (Cartesian) coordinates, and others may assume geographic (longitude/latitude) coordinates. We encourage the users to verify how coordinates are processed in the packages, as the consequences can be important in terms of spatial attributes (e.g. areas and angles)."

**Comment by rociojoo** [comment]
And the CTV is more general now. It refers to objects and individuals, and only when necessary, animals or humans.

**Comment by rociojoo** [comment]
And there is now an issue template to include new packages.

**Comment by edzer** [comment]
Instead of "areas and angles" I would mention "distance, speed and angles".

**Comment by rociojoo** [comment]
Done!

**Comment by rociojoo** [comment]
I'll close the issue if there is nothing more to add.
