### ISSUE TITLE
geoviz: Elevation and GPS Data Visualisation

### ISSUE THREAD

**Issue by basille** [rociojoo/CranTaskView-Track#3]
**Is it on CRAN?**
Yes. Also separate [home page](https://neilcharles.github.io/geoviz/).

**Are you the author of this package?**
No. 

**Additional information (optional):**
- In terms of the workflow (see Figure in the CTV), where should the package fit? Visualization.
- Could you give a brief description or mention functions corresponding to different sections in the CTV? Mostly the `add_gps_to_rayshader` function which does what its name implies.

**Comment by birderboone** [comment]
Thank you for your submission, we will let you know the status of the package after the next update!

**Comment by birderboone** [comment]
At this moment we're not considering this package a Tracking package as the main purpose of the package is not to visualize tracking data but to create elevation shaders. We encourage it to be submitted to another TaskView.
