### ISSUE TITLE
ctmmweb: Web App For ctmm

### ISSUE THREAD

**Issue by basille** [rociojoo/CranTaskView-Track#4]
**Is it on CRAN?**
No. [Home page](https://github.com/ctmm-initiative/ctmmweb) on GitHub.

**Are you the author of this package?**
No. 

**If you are the author, does it pass check tests?**
I don't know. 

**Additional information (optional):**

In terms of the workflow (see Figure in the CTV), where should the package fit? Post-processing / visualization / track description / space use.

Could you give a brief description or mention functions corresponding to different sections in the CTV? Main function is `ctmmweb::app()` which loads a Shiny app as an interface to the `ctmm` package. Functionalities include outlier removal, visualization of GPS points and home ranges, evaluation of autocorrelation and home-range estimation.

**Comment by birderboone** [comment]
Thank you for your submission, we'll add it to the list and update you on the status after the next update!

**Comment by birderboone** [comment]
While we agree this package belongs on the Tracking-CranTaskView, it did not pass cran checks. While the vignette built correctly, the cran checks were not happy with formatting choices at threw out a Warning. You can check the check.log at `checks/check_logs/ctmmweb_check.log` for more details. 

We will keep this on the list and rerun tests in January
