### ISSUE TITLE
stmove: Build reproducible reports for spatial-temporal animal movement analysis

### ISSUE THREAD

**Issue by basille** [rociojoo/CranTaskView-Track#5]
**Is it on CRAN?**
No. GitHub repository: https://github.com/dpseidel/stmove

**Are you the author of this package?**
No. 

**If you are the author, does it pass check tests?**
I don't know. 

**Additional information (optional):**
- In terms of the workflow (see Figure in the CTV), where should the package fit? Visualization and Track description.
- Could you give a brief description or mention functions corresponding to different sections in the CTV? The primary function of this package is `build_report` which, given a clean regularized trajectory, will deliver a .Rmd and .pdf report including basic path statistics, path visualizations, and a couple of home range analyses.

**Comment by birderboone** [comment]
Thanks for the submission, we'll add it to the list and let you know the status of the package we do our next update!

**Comment by birderboone** [comment]
While this package would fit in the Tracking CranTaskView, it unfortunately contained a vignette error so further cran checks could not be run. 

We will keep this package on the list, and see if it passes tests in January.

**Comment by rociojoo** [comment]
Ran the tests again. There were errors running the examples. You can check the check.log at `checks/check_logs/stmove_check.log` for more details.
