### ISSUE TITLE
rerddapXtracto: Extracts Environmental Data from 'ERDDAP' Web Services

### ISSUE THREAD

**Issue by rmendels** [rociojoo/CranTaskView-Track#6]
**Is it on CRAN?**
Yes: https://cran.r-project.org/package=rerddapXtracto

**Are you the author of this package?**
Yes
**If you are the author, does it pass check tests?**
Yes
**Additional information (optional):**
Package allows to extract along a track any environmental data served on any ERDDAP server.  This literally involves petabytes of environmental data,  including many very hi-res datasets

**Comment by birderboone** [comment]
Thanks for the submission. We're updating the taskview now and will update you on the status as soon as we know it!

**Comment by birderboone** [comment]
We agree this package does fit under the purview of the CranTaskView and the CTV should be updated shortly with it included.

Thanks for the package!
