### ISSUE TITLE
Rhabit: Estimation of animal habitat selection using the Langevin movement model

### ISSUE THREAD

**Issue by rociojoo** [rociojoo/CranTaskView-Track#8]
**Is it on CRAN?**  
No. It's on github https://github.com/papayoun/Rhabit

**Are you the author of this package?**  
No. 

**If you are the author, does it pass check CRAN tests?**  
I don't know. 

**Additional information:**  
It fits a continuous time movement model for resource selection and getting a utilization distribution. It could go under space use.

Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?  

It fits a continuous time movement model for resource selection and getting a utilization distribution. It could go under space use.
The main function is fit_langevin_ud. I personally think that the documentation should be improved for usability. The package has very few functions.

**Comment by birderboone** [comment]
Thanks for the submission. We're updating and now and will update you on the status when its available.

**Comment by birderboone** [comment]
We agree your package fits the purview of the Tracking CranTaskView, and it has passed checks successfully!

Thank the developers for their hard work! It will be added to the CTV shortly
