### ISSUE TITLE
vmstools: For analysing fisheries VMS (Vessel Monitoring System) data

### ISSUE THREAD

**Issue by rociojoo** [rociojoo/CranTaskView-Track#9]
**Is it on CRAN?**  
No. Github. https://github.com/nielshintzen/vmstools/tree/master/vmstools

**Are you the author of this package?**  
No. 

**If you are the author, does it pass check CRAN tests?**  
I don't know. 

**Additional information:**  
It is for logbook and VMS data. VMS is vessel monitoring system, basically GPS of fishing vessels. It has a lot of functions and I'm not familiar with all of them. Some are for computing variables such as bearings and distances, and doing different types of interpolations to the tracking data.

Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?  
It is described as " It is specifically developed to process, analyse and visualize logbooks and VMS data", so I think it fits as one of its main goals is to analyze tracking data (from fishing vessels).

In terms of the tracking workflow (see Figure in the CTV), where does the package fit? (Feel free to mention any particular functions and how they fit as well.)
bearing, calculateSpeed, distance,  compute bearings, speeds and distance so could go in postprocessing. 
calculate_mcp, mcp_area could go in space use
interCubicHermiteSpline	interpolates with cubic hermite spline and could also go in post-processing.

* There could be other sections were we could mention this package, so I would contact the author to encourage a submission to add stuff (for next time) if the package passes check test.

**Comment by birderboone** [comment]
While this behemoth of a package does fit under the purview of the Tracking CranTaskView, it did not pass cran checks and encountered a high number of errors/warnings. Anyone interested can check the check log at `checks/check_log/vmstools_check.log` for the details.

Thanks for the submission.
